apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-js
        image: laharisanapoori/lahari-js:latest
        ports:
        - containerPort: 3000
