apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: version1
  template:
    metadata:
      labels:
        app: version1
        color: blue
    spec:
      containers:
      - name: blue-container
        image: nginx:latest
        ports:
        - containerPort: 80
